### ISSUE TITLE
Add lookup functionality

### ISSUE THREAD

**Issue by Torie-Coding** [Torie-Coding/keepass#8]
The lookup functionality should be able to show entries of a group or find a single entry.
Also it should display the data of an entry.

**Comment by MPStudyly** [comment]
I'd really love to see this feature and am willing to spend some time tinkering around with it. Could you provide me with a few hints about where to hook into the code to get this realized? I've had a glance over the code and it seems it shouldn't be too hard to get things going. I've also noticed you have a branch with initial work on this topic. The diff wasn't too conclusive to me though as it was pretty minimal, but apparently not enough to have this working?

Anyway, I'd be glad to get some input and will look forward to submit a PR. :)

**Comment by Torie-Coding** [comment]
hey, thanks for your interest! I haven't been able to work on the project much recently and have had completely different challenges in my playbooks with this module. The keyword here is password generation based on specifications. I only opened this issue to remind myself that there is still something to do here. I would also merge the branch beforehand so that I have my current status in it. I also noticed that I have a documentation error in the module and that I should also clean up the project itself with the fragments and so on.

as you may notice, this is my first project and ansible module, so I still have a lot to do and learn.

to your question about getting started with the code. I think there are two approaches:
1. you build a new plugin called lookup
2. a new action is added to the respective plugin

from my point of view it shouldn't be that difficult because I already do it in development:
https://github.com/Torie-Coding/keepass/blob/ff2eb74f54008ce03024bee0be98a5119d3b734d/plugins/modules/entry.py#L269-L275

if you want to take a look at it then feel free to make a fork from master and if you have any questions then just write :)

EDIT: maybe i also rewrite the mentioned code with an override oder something

**Comment by MPStudyly** [comment]
Thank you for your quick reply!

> I also noticed that I have a documentation error in the module and that I should also clean up the project itself with the fragments and so on.
> as you may notice, this is my first project and ansible module, so I still have a lot to do and learn.

What error do you mean? I just started to play around with the module a little (just using it as it is rn), it seemed pretty straight forward so far.
Cleanups are something I encounter often in the context of Ansible ^^" We're already on our third major refactoring of Ansible configs within three years, which were mostly necessary due to past us not knowing better. You definitely will never have seen and known it all :joy: 
But as you mention it, I've noticed a few details that could be improved, such as defining mutually exclusive parameters and the way parameters are handed to the module in general, but don't worry. :)

> 
> to your question about getting started with the code. I think there are two approaches:
> 
>     1. you build a new plugin called lookup
> 
>     2. a new action is added to the respective plugin
> 
> 
> from my point of view it shouldn't be that difficult because I already do it in development:
> 
> https://github.com/Torie-Coding/keepass/blob/ff2eb74f54008ce03024bee0be98a5119d3b734d/plugins/modules/entry.py#L269-L275

That's what I've noticed too. Thus I think the additional action approach could be more straight forward. At least to get things going. :thinking: 

> if you want to take a look at it then feel free to make a fork from master and if you have any questions then just write :)

I'll continue fiddling around with it a little and then try a few things :+1: 

> EDIT: maybe i also rewrite the mentioned code with an override oder something

Good catch, how is this currently handled? Does create always overwrite?

**Comment by MPStudyly** [comment]
To keep you up to date on what's happening on my side: We found the current state of this very usable and do not even need a dedicated lookup (yet). Thus I won't start on code changes for now until we completed our internal project. :/
We'd still like to see the lookup happening, not only as an available action, but also as a dedicated lookup plugin with optional password creation along it, so stay assured that this won't get stuck in a dead end :) Having a single line/call within plays and roles would be way more convenient than having to perform a task and working with results (and injecting them into dicts with set_facts).

Regarding the error you mentioned, we didn't encounter one (affecting us) yet. ^^"

**Comment by Torie-Coding** [comment]
Hey, thanks for the trigger to start using the lookup plugin. Regarding the "bug" I mentioned: I forgot to show the "key file" example for entries and groups. That is now fixed :)

I just released version 1.2 where you can use the lookup plugin. If you have any problems then let me know.

**Comment by Torie-Coding** [comment]
Hey, thanks for the trigger to start using the lookup plugin. Regarding the "bug" I mentioned: I forgot to show the "key file" example for entries and groups. That is now fixed :)

I just released version 1.2 where you can use the lookup plugin. If you have any problems then let me know.

**Comment by MPStudyly** [comment]
Wow, thanks for making this happening! :D I'll have a look at it next week as I'm going into a short vacation over this weekend :) In case I'll encounter issues, I'll create a ticket.
